name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Build and prepare for deployment
      run: |
        cd my-app
        npm ci
        npm run build
        # 必要なファイルを準備
        mkdir -p deploy
        cp -r .next deploy/
        cp -r node_modules deploy/
        cp package.json deploy/
        cp next.config.js deploy/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-gen8-step4-pos-app-85'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: my-app/deploy
